[2022-12-05T15:35:17.166+0100] {processor.py:153} INFO - Started process (PID=324749) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:35:17.167+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:35:17.168+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:35:17.168+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:35:17.195+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:35:17.194+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:35:17.195+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:35:17.195+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:35:17.195+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:35:17.209+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-12-05T15:36:03.241+0100] {processor.py:153} INFO - Started process (PID=324821) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:36:03.245+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:36:03.247+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:36:03.247+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:36:03.286+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:36:03.285+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:36:03.286+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:36:03.286+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:36:03.286+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:36:03.310+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2022-12-05T15:36:45.900+0100] {processor.py:153} INFO - Started process (PID=324881) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:36:45.902+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:36:45.902+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:36:45.902+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:36:45.933+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:36:45.932+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:36:45.934+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:36:45.934+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:36:45.934+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:36:45.949+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2022-12-05T15:37:29.313+0100] {processor.py:153} INFO - Started process (PID=324959) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:37:29.314+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:37:29.317+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:37:29.315+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:37:29.349+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:37:29.348+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:37:29.349+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:37:29.349+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:37:29.349+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:37:29.362+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2022-12-05T15:38:08.897+0100] {processor.py:153} INFO - Started process (PID=325023) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:38:08.898+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:38:08.899+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:38:08.899+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:38:08.929+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:38:08.928+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:38:08.929+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:38:08.929+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:38:08.930+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:38:08.946+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2022-12-05T15:38:55.499+0100] {processor.py:153} INFO - Started process (PID=325117) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:38:55.500+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:38:55.501+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:38:55.501+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:38:55.526+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:38:55.526+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:38:55.527+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:38:55.527+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:38:55.527+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:38:55.539+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-12-05T15:39:36.305+0100] {processor.py:153} INFO - Started process (PID=325176) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:39:36.309+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:39:36.310+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:39:36.310+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:39:36.340+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:39:36.339+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:39:36.340+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:39:36.340+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:39:36.341+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:39:36.366+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2022-12-05T15:40:22.427+0100] {processor.py:153} INFO - Started process (PID=325247) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:40:22.429+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:40:22.429+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:40:22.429+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:40:22.456+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:40:22.455+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:40:22.456+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:40:22.456+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:40:22.457+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:40:22.470+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-05T15:41:08.266+0100] {processor.py:153} INFO - Started process (PID=325330) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:41:08.268+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:41:08.268+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:41:08.268+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:41:08.295+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:41:08.295+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:41:08.296+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:41:08.295+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:41:08.296+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:41:08.311+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2022-12-05T15:41:51.104+0100] {processor.py:153} INFO - Started process (PID=325440) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:41:51.105+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:41:51.106+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:41:51.106+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:41:51.142+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:41:51.141+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:41:51.142+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:41:51.142+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:41:51.143+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:41:51.156+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2022-12-05T15:42:33.997+0100] {processor.py:153} INFO - Started process (PID=325497) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:42:34.000+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:42:34.001+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:42:34.001+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:42:34.034+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:42:34.033+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:42:34.034+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:42:34.034+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:42:34.035+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:42:34.053+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2022-12-05T15:43:11.931+0100] {processor.py:153} INFO - Started process (PID=325541) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:43:11.932+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:43:11.933+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:43:11.933+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:43:11.966+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:43:11.965+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:43:11.966+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:43:11.966+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:43:11.966+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:43:11.989+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2022-12-05T15:43:55.463+0100] {processor.py:153} INFO - Started process (PID=325621) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:43:55.465+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:43:55.466+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:43:55.466+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:43:55.500+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:43:55.497+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:43:55.501+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:43:55.501+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:43:55.502+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:43:55.519+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2022-12-05T15:44:33.805+0100] {processor.py:153} INFO - Started process (PID=325667) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:44:33.807+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:44:33.808+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:44:33.808+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:44:33.836+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:44:33.835+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:44:33.836+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:44:33.836+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:44:33.836+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:44:33.853+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-12-05T15:45:12.039+0100] {processor.py:153} INFO - Started process (PID=325714) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:45:12.041+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:45:12.041+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:45:12.041+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:45:12.070+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:45:12.069+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:45:12.071+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:45:12.071+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:45:12.071+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:45:12.088+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2022-12-05T15:45:56.524+0100] {processor.py:153} INFO - Started process (PID=325774) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:45:56.526+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:45:56.526+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:45:56.526+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:45:56.569+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:45:56.568+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:45:56.570+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:45:56.570+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:45:56.570+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:45:56.589+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2022-12-05T15:46:34.626+0100] {processor.py:153} INFO - Started process (PID=325825) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:46:34.627+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:46:34.628+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:46:34.628+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:46:34.656+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:46:34.655+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:46:34.657+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:46:34.657+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:46:34.657+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:46:34.673+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-12-05T15:47:11.130+0100] {processor.py:153} INFO - Started process (PID=325870) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:47:11.132+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:47:11.132+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:47:11.132+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:47:11.161+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:47:11.160+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:47:11.161+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:47:11.161+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:47:11.161+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:47:11.181+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2022-12-05T15:47:46.730+0100] {processor.py:153} INFO - Started process (PID=325911) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:47:46.732+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:47:46.732+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:47:46.732+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:47:46.766+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:47:46.765+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:47:46.767+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:47:46.767+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:47:46.767+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:47:46.784+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2022-12-05T15:48:25.850+0100] {processor.py:153} INFO - Started process (PID=325969) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:48:25.853+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:48:25.854+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:48:25.854+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:48:25.886+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:48:25.885+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:48:25.887+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:48:25.887+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:48:25.887+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:48:25.901+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2022-12-05T15:49:07.987+0100] {processor.py:153} INFO - Started process (PID=326042) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:49:07.990+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:49:07.991+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:49:07.991+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:49:08.022+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:49:08.021+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:49:08.023+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:49:08.023+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:49:08.023+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:49:08.037+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2022-12-05T15:49:43.244+0100] {processor.py:153} INFO - Started process (PID=326084) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:49:43.246+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:49:43.246+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:49:43.246+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:49:43.277+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:49:43.276+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:49:43.277+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:49:43.277+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:49:43.278+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:49:43.294+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2022-12-05T15:50:19.515+0100] {processor.py:153} INFO - Started process (PID=326130) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:50:19.516+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:50:19.517+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:50:19.517+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:50:19.548+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:50:19.547+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:50:19.548+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:50:19.548+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:50:19.549+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:50:19.574+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2022-12-05T15:50:57.153+0100] {processor.py:153} INFO - Started process (PID=326189) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:50:57.154+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:50:57.155+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:50:57.155+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:50:57.181+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:50:57.181+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:50:57.181+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:50:57.181+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:50:57.182+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:50:57.199+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2022-12-05T15:51:33.533+0100] {processor.py:153} INFO - Started process (PID=326232) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:51:33.534+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:51:33.535+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:51:33.535+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:51:33.562+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:51:33.561+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:51:33.562+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:51:33.562+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:51:33.562+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:51:33.579+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2022-12-05T15:52:11.906+0100] {processor.py:153} INFO - Started process (PID=326279) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:52:11.908+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:52:11.909+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:52:11.909+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:52:11.933+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:52:11.932+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:52:11.933+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:52:11.933+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:52:11.933+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:52:11.946+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-12-05T15:52:58.134+0100] {processor.py:153} INFO - Started process (PID=326333) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:52:58.136+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:52:58.137+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:52:58.137+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:52:58.176+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:52:58.175+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:52:58.176+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:52:58.176+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:52:58.176+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:52:58.189+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2022-12-05T15:53:38.456+0100] {processor.py:153} INFO - Started process (PID=326413) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:53:38.460+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:53:38.462+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:53:38.461+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:53:38.500+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:53:38.500+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:53:38.501+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:53:38.501+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:53:38.501+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:53:38.521+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2022-12-05T15:54:20.475+0100] {processor.py:153} INFO - Started process (PID=326462) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:54:20.477+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:54:20.478+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:54:20.477+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:54:20.509+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:54:20.507+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:54:20.509+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:54:20.509+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:54:20.509+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:54:20.525+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2022-12-05T15:55:04.357+0100] {processor.py:153} INFO - Started process (PID=326518) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:55:04.358+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:55:04.359+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:55:04.359+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:55:04.401+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:55:04.399+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:55:04.401+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:55:04.401+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:55:04.402+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:55:04.424+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2022-12-05T15:55:46.718+0100] {processor.py:153} INFO - Started process (PID=326574) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:55:46.721+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:55:46.723+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:55:46.722+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:55:46.758+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:55:46.758+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:55:46.759+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:55:46.759+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:55:46.759+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:55:46.771+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2022-12-05T15:56:23.787+0100] {processor.py:153} INFO - Started process (PID=326619) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:56:23.789+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:56:23.791+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:56:23.790+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:56:23.821+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:56:23.820+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:56:23.821+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:56:23.821+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:56:23.822+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:56:23.834+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-12-05T15:57:02.915+0100] {processor.py:153} INFO - Started process (PID=326670) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:57:02.916+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:57:02.917+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:57:02.917+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:57:02.944+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:57:02.943+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:57:02.944+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:57:02.944+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:57:02.944+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:57:02.963+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2022-12-05T15:57:40.094+0100] {processor.py:153} INFO - Started process (PID=326713) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:57:40.096+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:57:40.096+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:57:40.096+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:57:40.122+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:57:40.122+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:57:40.123+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:57:40.122+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:57:40.123+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:57:40.140+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2022-12-05T15:58:23.392+0100] {processor.py:153} INFO - Started process (PID=326768) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:58:23.400+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:58:23.401+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:58:23.401+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:58:23.428+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:58:23.427+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:58:23.428+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:58:23.428+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:58:23.428+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:58:23.444+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2022-12-05T15:59:08.322+0100] {processor.py:153} INFO - Started process (PID=326852) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:59:08.324+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:59:08.325+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:59:08.325+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:59:08.353+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:59:08.352+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:59:08.353+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:59:08.353+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:59:08.353+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:59:08.369+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2022-12-05T15:59:49.217+0100] {processor.py:153} INFO - Started process (PID=326901) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:59:49.220+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T15:59:49.221+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:59:49.220+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:59:49.250+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:59:49.249+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T15:59:49.250+0100] {logging_mixin.py:137} INFO - [2022-12-05T15:59:49.250+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T15:59:49.251+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T15:59:49.268+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2022-12-05T16:00:31.530+0100] {processor.py:153} INFO - Started process (PID=326954) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:00:31.532+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:00:31.533+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:00:31.533+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:00:31.560+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:00:31.559+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:00:31.561+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:00:31.561+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:00:31.561+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:00:31.577+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2022-12-05T16:01:12.441+0100] {processor.py:153} INFO - Started process (PID=327004) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:01:12.443+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:01:12.444+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:01:12.444+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:01:12.473+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:01:12.472+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:01:12.473+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:01:12.473+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:01:12.474+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:01:12.493+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2022-12-05T16:01:51.901+0100] {processor.py:153} INFO - Started process (PID=327050) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:01:51.903+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:01:51.905+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:01:51.904+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:01:51.935+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:01:51.934+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:01:51.935+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:01:51.935+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:01:51.935+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:01:51.951+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2022-12-05T16:02:27.387+0100] {processor.py:153} INFO - Started process (PID=327091) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:02:27.388+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:02:27.389+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:02:27.389+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:02:27.418+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:02:27.417+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:02:27.418+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:02:27.418+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:02:27.419+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:02:27.435+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2022-12-05T16:03:06.691+0100] {processor.py:153} INFO - Started process (PID=327139) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:03:06.692+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:03:06.693+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:03:06.693+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:03:06.719+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:03:06.718+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:03:06.719+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:03:06.719+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:03:06.720+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:03:06.738+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2022-12-05T16:03:54.608+0100] {processor.py:153} INFO - Started process (PID=327224) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:03:54.611+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:03:54.612+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:03:54.611+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:03:54.644+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:03:54.643+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:03:54.645+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:03:54.645+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:03:54.645+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:03:54.663+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2022-12-05T16:04:36.721+0100] {processor.py:153} INFO - Started process (PID=327276) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:04:36.722+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:04:36.723+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:04:36.723+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:04:36.758+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:04:36.757+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:04:36.758+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:04:36.758+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:04:36.759+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:04:36.778+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2022-12-05T16:05:17.168+0100] {processor.py:153} INFO - Started process (PID=327325) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:05:17.177+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:05:17.178+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:05:17.178+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:05:17.218+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:05:17.217+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:05:17.219+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:05:17.219+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:05:17.219+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:05:17.234+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2022-12-05T16:05:56.840+0100] {processor.py:153} INFO - Started process (PID=327384) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:05:56.842+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:05:56.843+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:05:56.842+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:05:56.871+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:05:56.870+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:05:56.871+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:05:56.871+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:05:56.872+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:05:56.885+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-12-05T16:06:41.289+0100] {processor.py:153} INFO - Started process (PID=327437) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:06:41.290+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:06:41.291+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:06:41.291+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:06:41.319+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:06:41.319+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:06:41.320+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:06:41.320+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:06:41.320+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:06:41.332+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-05T16:07:18.752+0100] {processor.py:153} INFO - Started process (PID=327480) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:07:18.754+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:07:18.755+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:07:18.755+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:07:18.784+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:07:18.783+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:07:18.784+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:07:18.784+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:07:18.784+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:07:18.795+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-12-05T16:07:58.818+0100] {processor.py:153} INFO - Started process (PID=327531) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:07:58.820+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:07:58.820+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:07:58.820+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:07:58.850+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:07:58.849+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:07:58.850+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:07:58.850+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:07:58.850+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:07:58.862+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-05T16:08:42.909+0100] {processor.py:153} INFO - Started process (PID=327614) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:08:42.911+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:08:42.912+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:08:42.911+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:08:42.941+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:08:42.940+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:08:42.941+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:08:42.941+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:08:42.941+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:08:42.952+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-12-05T16:09:18.381+0100] {processor.py:153} INFO - Started process (PID=327657) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:09:18.383+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:09:18.384+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:09:18.384+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:09:18.413+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:09:18.412+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:09:18.413+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:09:18.413+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:09:18.414+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:09:18.427+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-12-05T16:09:54.397+0100] {processor.py:153} INFO - Started process (PID=327703) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:09:54.399+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:09:54.400+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:09:54.399+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:09:54.428+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:09:54.427+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:09:54.428+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:09:54.428+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:09:54.429+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:09:54.440+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-12-05T16:10:36.878+0100] {processor.py:153} INFO - Started process (PID=327759) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:10:36.879+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:10:36.879+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:10:36.879+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:10:36.900+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:10:36.900+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:10:36.900+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:10:36.900+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:10:36.901+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:10:36.911+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2022-12-05T16:11:13.260+0100] {processor.py:153} INFO - Started process (PID=327810) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:11:13.262+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:11:13.263+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:11:13.263+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:11:13.292+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:11:13.291+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:11:13.292+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:11:13.292+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:11:13.292+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:11:13.303+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-05T16:11:58.449+0100] {processor.py:153} INFO - Started process (PID=327900) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:11:58.450+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:11:58.451+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:11:58.451+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:11:58.478+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:11:58.478+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:11:58.479+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:11:58.478+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:11:58.479+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:11:58.490+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-12-05T16:12:41.895+0100] {processor.py:153} INFO - Started process (PID=327976) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:12:41.897+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:12:41.898+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:12:41.897+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:12:41.923+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:12:41.922+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:12:41.923+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:12:41.923+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:12:41.923+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:12:41.934+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-12-05T16:13:18.535+0100] {processor.py:153} INFO - Started process (PID=328024) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:13:18.537+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:13:18.538+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:13:18.538+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:13:18.572+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:13:18.572+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:13:18.573+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:13:18.573+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:13:18.573+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:13:18.587+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2022-12-05T16:14:01.923+0100] {processor.py:153} INFO - Started process (PID=328193) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:14:01.925+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:14:01.925+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:14:01.925+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:14:01.947+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:14:01.946+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:14:01.947+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:14:01.947+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:14:01.947+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:14:01.958+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-12-05T16:14:39.371+0100] {processor.py:153} INFO - Started process (PID=328247) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:14:39.372+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:14:39.373+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:14:39.373+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:14:39.402+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:14:39.402+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:14:39.403+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:14:39.402+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:14:39.403+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:14:39.413+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-12-05T16:15:19.774+0100] {processor.py:153} INFO - Started process (PID=328299) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:15:19.776+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:15:19.777+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:15:19.777+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:15:19.806+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:15:19.806+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:15:19.807+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:15:19.807+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:15:19.807+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:15:19.820+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-12-05T16:15:55.279+0100] {processor.py:153} INFO - Started process (PID=328365) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:15:55.281+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:15:55.282+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:15:55.282+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:15:55.310+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:15:55.310+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:15:55.311+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:15:55.311+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:15:55.311+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:15:55.325+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-12-05T16:16:37.089+0100] {processor.py:153} INFO - Started process (PID=328430) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:16:37.090+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:16:37.091+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:16:37.091+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:16:37.114+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:16:37.114+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:16:37.115+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:16:37.115+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:16:37.115+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:16:37.129+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-12-05T16:17:20.017+0100] {processor.py:153} INFO - Started process (PID=328484) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:17:20.018+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:17:20.019+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:17:20.019+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:17:20.039+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:17:20.039+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:17:20.039+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:17:20.039+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:17:20.040+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:17:20.050+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2022-12-05T16:18:00.614+0100] {processor.py:153} INFO - Started process (PID=328534) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:18:00.615+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:18:00.616+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:00.615+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:18:00.637+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:00.636+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:18:00.637+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:00.637+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:18:00.637+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:18:00.647+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2022-12-05T16:18:45.856+0100] {processor.py:153} INFO - Started process (PID=328626) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:18:45.858+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:18:45.859+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:45.858+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:18:45.888+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:45.887+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:18:45.888+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:18:45.888+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:18:45.888+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:18:45.898+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-12-05T16:19:31.558+0100] {processor.py:153} INFO - Started process (PID=328684) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:19:31.559+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:19:31.560+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:31.560+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:19:31.590+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:31.589+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:19:31.590+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:19:31.590+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:19:31.591+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:19:31.604+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-12-05T16:20:18.181+0100] {processor.py:153} INFO - Started process (PID=328758) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:20:18.182+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:20:18.183+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:18.183+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:20:18.212+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:18.212+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:20:18.213+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:20:18.212+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:20:18.213+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:20:18.226+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-12-05T16:21:06.677+0100] {processor.py:153} INFO - Started process (PID=328831) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:21:06.678+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:21:06.679+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:06.679+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:21:06.706+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:06.705+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:21:06.706+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:06.706+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:21:06.706+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:21:06.717+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-12-05T16:21:55.336+0100] {processor.py:153} INFO - Started process (PID=328901) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:21:55.338+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:21:55.339+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:55.339+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:21:55.368+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:55.367+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:21:55.368+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:21:55.368+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:21:55.368+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:21:55.383+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-12-05T16:22:43.684+0100] {processor.py:153} INFO - Started process (PID=329030) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:22:43.686+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:22:43.687+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:43.686+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:22:43.717+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:43.716+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:22:43.717+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:22:43.717+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:22:43.717+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:22:43.730+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-12-05T16:23:32.286+0100] {processor.py:153} INFO - Started process (PID=329152) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:23:32.287+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:23:32.288+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:32.288+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:23:32.316+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:32.316+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:23:32.317+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:23:32.316+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:23:32.317+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:23:32.328+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-05T16:24:18.470+0100] {processor.py:153} INFO - Started process (PID=329230) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:24:18.471+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:24:18.472+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:18.472+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:24:18.494+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:18.494+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:24:18.494+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:24:18.494+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:24:18.495+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:24:18.506+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2022-12-05T16:25:06.663+0100] {processor.py:153} INFO - Started process (PID=329332) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:25:06.664+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:25:06.665+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:06.665+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:25:06.685+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:06.685+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:25:06.686+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:06.685+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:25:06.686+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:25:06.696+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2022-12-05T16:25:55.075+0100] {processor.py:153} INFO - Started process (PID=329405) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:25:55.076+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:25:55.078+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:55.077+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:25:55.099+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:55.098+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:25:55.099+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:25:55.099+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:25:55.099+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:25:55.110+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-12-05T16:26:47.260+0100] {processor.py:153} INFO - Started process (PID=329469) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:26:47.262+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:26:47.262+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:47.262+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:26:47.283+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:47.283+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:26:47.284+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:26:47.283+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:26:47.284+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:26:47.294+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2022-12-05T16:27:39.333+0100] {processor.py:153} INFO - Started process (PID=329537) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:27:39.335+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:27:39.335+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:39.335+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:27:39.364+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:39.364+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:27:39.365+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:27:39.364+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:27:39.365+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:27:39.376+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-05T16:28:26.051+0100] {processor.py:153} INFO - Started process (PID=329599) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:28:26.053+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:28:26.054+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:26.053+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:28:26.087+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:26.086+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:28:26.087+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:28:26.087+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:28:26.087+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:28:26.101+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2022-12-05T16:29:18.222+0100] {processor.py:153} INFO - Started process (PID=329753) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:29:18.224+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:29:18.225+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:18.224+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:29:18.254+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:18.254+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:29:18.255+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:29:18.254+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:29:18.255+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:29:18.268+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-12-05T16:30:06.562+0100] {processor.py:153} INFO - Started process (PID=329815) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:30:06.563+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:30:06.564+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:06.564+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:30:06.587+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:06.587+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:30:06.587+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:30:06.587+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:30:06.588+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:30:06.604+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-12-05T16:31:03.566+0100] {processor.py:153} INFO - Started process (PID=329884) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:31:03.572+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:31:03.573+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:31:03.573+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:31:03.608+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:31:03.607+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:31:03.608+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:31:03.608+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:31:03.608+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:31:03.621+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2022-12-05T16:42:38.966+0100] {processor.py:153} INFO - Started process (PID=330395) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:42:38.967+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:42:38.968+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:42:38.968+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:42:38.997+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:42:38.996+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:42:38.997+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:42:38.997+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:42:38.998+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:42:39.018+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2022-12-05T16:43:20.971+0100] {processor.py:153} INFO - Started process (PID=330443) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:43:20.972+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:43:20.973+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:43:20.973+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:43:20.998+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:43:20.998+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:43:20.999+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:43:20.999+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:43:20.999+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:43:21.014+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-05T16:44:04.186+0100] {processor.py:153} INFO - Started process (PID=330547) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:44:04.188+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:44:04.188+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:44:04.188+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:44:04.211+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:44:04.210+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:44:04.211+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:44:04.211+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:44:04.211+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:44:04.227+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-12-05T16:44:45.924+0100] {processor.py:153} INFO - Started process (PID=330594) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:44:45.926+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:44:45.927+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:44:45.926+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:44:45.951+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:44:45.951+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:44:45.951+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:44:45.951+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:44:45.952+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:44:45.968+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-12-05T16:45:26.357+0100] {processor.py:153} INFO - Started process (PID=330644) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:45:26.362+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:45:26.363+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:45:26.363+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:45:26.395+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:45:26.394+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:45:26.395+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:45:26.395+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:45:26.396+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:45:26.417+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2022-12-05T16:46:08.068+0100] {processor.py:153} INFO - Started process (PID=330725) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:46:08.072+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:46:08.073+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:46:08.072+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:46:08.104+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:46:08.103+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:46:08.105+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:46:08.104+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:46:08.105+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:46:08.122+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2022-12-05T16:46:53.403+0100] {processor.py:153} INFO - Started process (PID=330787) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:46:53.406+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:46:53.407+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:46:53.407+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:46:53.442+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:46:53.440+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:46:53.442+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:46:53.442+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:46:53.442+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:46:53.457+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2022-12-05T16:47:39.071+0100] {processor.py:153} INFO - Started process (PID=330834) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:47:39.074+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:47:39.075+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:47:39.074+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:47:39.106+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:47:39.105+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:47:39.107+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:47:39.107+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:47:39.107+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:47:39.120+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2022-12-05T16:48:11.715+0100] {processor.py:153} INFO - Started process (PID=330867) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:48:11.716+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:48:11.717+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:48:11.717+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:48:11.749+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:48:11.747+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:48:11.750+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:48:11.749+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:48:11.750+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:48:11.770+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2022-12-05T16:48:55.304+0100] {processor.py:153} INFO - Started process (PID=330946) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:48:55.310+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:48:55.311+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:48:55.311+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:48:55.351+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:48:55.351+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:48:55.352+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:48:55.351+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:48:55.352+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:48:55.370+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2022-12-05T16:57:55.691+0100] {processor.py:153} INFO - Started process (PID=331318) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:57:55.693+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:57:55.694+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:57:55.694+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:57:55.717+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:57:55.716+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:57:55.717+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:57:55.717+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:57:55.718+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:57:55.728+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2022-12-05T16:58:41.163+0100] {processor.py:153} INFO - Started process (PID=331393) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:58:41.165+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:58:41.165+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:41.165+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:58:41.191+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:41.191+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:58:41.192+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:58:41.191+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:58:41.192+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:58:41.207+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2022-12-05T16:59:28.113+0100] {processor.py:153} INFO - Started process (PID=331444) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:59:28.115+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T16:59:28.116+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:28.116+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:59:28.153+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:28.152+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T16:59:28.153+0100] {logging_mixin.py:137} INFO - [2022-12-05T16:59:28.153+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T16:59:28.154+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T16:59:28.166+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2022-12-05T17:12:37.228+0100] {processor.py:153} INFO - Started process (PID=332070) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T17:12:37.229+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T17:12:37.230+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:37.230+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T17:12:37.262+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:37.262+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T17:12:37.262+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:12:37.262+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T17:12:37.263+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T17:12:37.285+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2022-12-05T17:34:30.689+0100] {processor.py:153} INFO - Started process (PID=335376) to work on /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T17:34:30.692+0100] {processor.py:743} INFO - Processing file /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-12-05T17:34:30.697+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:34:30.697+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T17:34:30.731+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:34:30.730+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-12-05T17:34:30.731+0100] {logging_mixin.py:137} INFO - [2022-12-05T17:34:30.731+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-12-05T17:34:30.732+0100] {processor.py:755} WARNING - No viable dags retrieved from /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-12-05T17:34:30.745+0100] {processor.py:175} INFO - Processing /home/andria/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
